import { Video, Channel } from '@/types'

/**
 * Mock data for local development and demo mode
 * When NEXT_PUBLIC_YOUTUBE_API_KEY is not set, the app falls back to this mock data
 */

export const MOCK_CHANNELS: Channel[] = [
  {
    id: '1',
    youtube_channel_id: 'UC2_QH-J0eoWQTxx5sKRAQzA',
    title: 'Vergecast',
    handle: '@vergecast',
    description: 'The Verge\'s weekly technology podcast discussing the latest tech news and gadgets.',
    thumbnail_url:
      'https://yt4.ggpht.com/ytc/AOPolaT4oevK3w3XDFvTfUZXP1i5qEE5yZvT0yfaqg=s800-c-k-c0x00ffffff-no-rj',
    uploads_playlist_id: 'UU2_QH-J0eoWQTxx5sKRAQzA',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    youtube_channel_id: 'UCR1IuLEqb0dxn4SM0P7Q5Pw',
    title: 'Kurzgesagt – In a Nutshell',
    handle: '@kurzgesagt',
    description: 'Educational videos about science, philosophy, and current events explained in 5-10 minutes.',
    thumbnail_url:
      'https://yt4.ggpht.com/ytc/AOPolaEPxCsY4xG3d1TjNLmDyLMZHXNQyJ_Jc2O3Soc=s800-c-k-c0x00ffffff-no-rj',
    uploads_playlist_id: 'UUR1IuLEqb0dxn4SM0P7Q5Pw',
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    youtube_channel_id: 'UCRA1qvkqxjLk_8MqM4J_0TQ',
    title: 'Ali Abdaal',
    handle: '@aliabdaal',
    description: 'Videos about productivity, deep work, and personal development for creators and knowledge workers.',
    thumbnail_url:
      'https://yt4.ggpht.com/ytc/AOPolaFmU3Ov7GqWCXPMOoNqbITLKhq0vJlN1lXqxw=s800-c-k-c0x00ffffff-no-rj',
    uploads_playlist_id: 'UURA1qvkqxjLk_8MqM4J_0TQ',
    created_at: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const MOCK_VIDEOS: Video[] = [
  {
    id: '1',
    youtube_video_id: 'dQw4w9WgXcQ',
    youtube_channel_id: 'UC2_QH-J0eoWQTxx5sKRAQzA',
    channel_title: 'Vergecast',
    title: 'The best tech of 2024 so far',
    description:
      'We dive into the technology that actually mattered in the first half of 2024, from AI breakthroughs to hardware innovations. This episode covers Apple Vision Pro experiences, latest GPU releases, and upcoming releases that we are excited about.',
    thumbnail_url: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg',
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    duration_text: '1:32:15',
    duration_seconds: 5535,
    video_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    transcript_status: 'extracted',
    transcript_text: 'Tech industry leaders discuss the most important technological innovations of 2024, emphasizing AI advancements, hardware improvements, and their potential impact on future development.',
    summary_status: 'complete',
    summary_text:
      'Tech industry leaders discuss the most important technological innovations of 2024, emphasizing AI advancements, hardware improvements, and their potential impact on future development.',
    summary_source_type: 'transcript',
    summarized_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    youtube_video_id: 'jNQXAC9IVRw',
    youtube_channel_id: 'UCR1IuLEqb0dxn4SM0P7Q5Pw',
    channel_title: 'Kurzgesagt – In a Nutshell',
    title: 'How Energy Shapes Civilization',
    description:
      'Energy is the lifeblood of civilization. But what exactly is energy? And how did we go from burning wood to splitting atoms? This video explores the history and physics of energy, and how it has shaped human civilization.',
    thumbnail_url: 'https://i.ytimg.com/vi/jNQXAC9IVRw/maxresdefault.jpg',
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    duration_text: '10:15',
    duration_seconds: 615,
    video_url: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
    transcript_status: 'extracted',
    transcript_text: 'Exploration of how energy has fundamentally shaped human civilization, from early wood burning to modern nuclear power generation, examining the physics and societal implications of different energy sources.',
    summary_status: 'complete',
    summary_text:
      'Exploration of how energy has fundamentally shaped human civilization, from early wood burning to modern nuclear power generation, examining the physics and societal implications of different energy sources.',
    summary_source_type: 'transcript',
    summarized_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    youtube_video_id: '9bZkp7q19f0',
    youtube_channel_id: 'UCRA1qvkqxjLk_8MqM4J_0TQ',
    channel_title: 'Ali Abdaal',
    title: 'The Secret to Deep Work',
    description:
      'Deep work is the key to productivity and success in the modern world. In this video, I break down the principles of deep work from Cal Newport\'s book and share practical strategies to implement them in your life.',
    thumbnail_url: 'https://i.ytimg.com/vi/9bZkp7q19f0/maxresdefault.jpg',
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    duration_text: '14:32',
    duration_seconds: 872,
    video_url: 'https://www.youtube.com/watch?v=9bZkp7q19f0',
    transcript_status: 'extracted',
    transcript_text: 'Deep work principles enable sustainable productivity and meaningful achievement. The video outlines strategies based on Cal Newport\'s framework for maintaining focus, eliminating distractions, and producing high-quality output.',
    summary_status: 'complete',
    summary_text:
      'Deep work principles enable sustainable productivity and meaningful achievement. The video outlines strategies based on Cal Newport\'s framework for maintaining focus, eliminating distractions, and producing high-quality output.',
    summary_source_type: 'transcript',
    summarized_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    youtube_video_id: 'kffacxfA7g4',
    youtube_channel_id: 'UC2_QH-J0eoWQTxx5sKRAQzA',
    channel_title: 'Vergecast',
    title: 'Apple\'s AI strategy revealed',
    description:
      'After months of speculation, Apple has finally announced its artificial intelligence strategy. We analyze what Apple Intelligence means for your iPhone and whether the company can catch up to Google and OpenAI.',
    thumbnail_url: 'https://i.ytimg.com/vi/kffacxfA7g4/maxresdefault.jpg',
    published_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    duration_text: '1:45:20',
    duration_seconds: 6320,
    video_url: 'https://www.youtube.com/watch?v=kffacxfA7g4',
    transcript_status: null,
    summary_status: null,
    summary_text: undefined,
    summary_source_type: null,
    summarized_at: undefined,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    youtube_video_id: '3mXBVVU1dJU',
    youtube_channel_id: 'UCR1IuLEqb0dxn4SM0P7Q5Pw',
    channel_title: 'Kurzgesagt – In a Nutshell',
    title: 'What if you stopped sleeping?',
    description:
      'Sleep is one of the most essential biological processes we know. But what happens if you stop sleeping? We explore the science of sleep deprivation and why sleep is critical for your health and survival.',
    thumbnail_url: 'https://i.ytimg.com/vi/3mXBVVU1dJU/maxresdefault.jpg',
    published_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    duration_text: '9:47',
    duration_seconds: 587,
    video_url: 'https://www.youtube.com/watch?v=3mXBVVU1dJU',
    transcript_status: 'extracted',
    transcript_text: 'Sleep deprivation has severe consequences for mental and physical health, affecting cognitive function, immune system, and overall well-being. The video explains the biological necessity of sleep.',
    summary_status: 'complete',
    summary_text:
      'Sleep deprivation has severe consequences for mental and physical health, affecting cognitive function, immune system, and overall well-being. The video explains the biological necessity of sleep.',
    summary_source_type: 'transcript',
    summarized_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    youtube_video_id: 'IgIkj5PTZPQ',
    youtube_channel_id: 'UCRA1qvkqxjLk_8MqM4J_0TQ',
    channel_title: 'Ali Abdaal',
    title: 'Building an audience while working full-time',
    description:
      'The challenge of building an audience while working a full-time job is real. In this video, I share practical strategies and time management techniques that helped me grow my channel to hundreds of thousands of subscribers.',
    thumbnail_url: 'https://i.ytimg.com/vi/IgIkj5PTZPQ/maxresdefault.jpg',
    published_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    duration_text: '16:45',
    duration_seconds: 1005,
    video_url: 'https://www.youtube.com/watch?v=IgIkj5PTZPQ',
    transcript_status: 'extracted',
    transcript_text: 'Building a creator audience requires strategic time management and consistency. The video provides actionable frameworks for balancing full-time work with content creation through prioritization and efficient workflows.',
    summary_status: 'complete',
    summary_text:
      'Building a creator audience requires strategic time management and consistency. The video provides actionable frameworks for balancing full-time work with content creation through prioritization and efficient workflows.',
    summary_source_type: 'transcript',
    summarized_at: new Date().toISOString(),
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    youtube_video_id: 'ZA8tNiVcxfU',
    youtube_channel_id: 'UC2_QH-J0eoWQTxx5sKRAQzA',
    channel_title: 'Vergecast',
    title: 'The future of wearable technology',
    description:
      'Wearables are becoming increasingly sophisticated. We discuss the latest smartwatches, AR glasses, and health tracking devices that are shaping the future of human-computer interaction.',
    thumbnail_url: 'https://i.ytimg.com/vi/ZA8tNiVcxfU/maxresdefault.jpg',
    published_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    duration_text: '1:28:50',
    duration_seconds: 5330,
    video_url: 'https://www.youtube.com/watch?v=ZA8tNiVcxfU',
    transcript_status: null,
    summary_status: null,
    summary_text: undefined,
    summary_source_type: null,
    summarized_at: undefined,
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]
